### ISSUE TITLE
Cannot read property 'shadowRoot' of null

### ISSUE THREAD

**Issue by x99percent** [thomasloven/lovelace-card-tools#4]
Not sure what's causing it, but this error pops up in my HA log from time to time. 

``https://[REDACTED]/local/lovelace-card-tools/card-tools.js:42:9 Uncaught TypeError: Cannot read property 'shadowRoot' of null``

**Comment by pilotak** [comment]
i have similar: `http://192.168.3.10:8123/local/card-tools.js:41:21 TypeError: document.querySelector(...).shadowRoot.querySelector(...).shadowRoot.querySelector(...).shadowRoot.querySelector(...) is null`

**Comment by tungmeister** [comment]
Also seeing this quite frequently.

**Comment by mf-social** [comment]
I've been getting this for a few days too, but only on the page with a picture-elements card on it.  This is also the only page that has `panel: true` too.

**Comment by thomasloven** [comment]
Should be fixed now.

**Comment by LeidenSpain** [comment]
Hi,

I just updated the card, and the same error appears:
```
og Details (ERROR)
Mon Mar 18 2019 09:11:43 GMT+0100 (hora estándar de Europa central)
https://xxxxxx.us:8123/local/custom_ui/card-tools.js?track=true:69:7 Uncaught TypeError: Cannot read property 'shadowRoot' of null
```

Regards

**Comment by thomasloven** [comment]
It is entirely impossible for that error to appear if you have a version of card-tools which is less than 7 days old. It is even more impossible to get it on line 69 in the latest version, since that line doesn't contain `shadowRoot` in any way.

Try actually updating. And please open a new issue if you suspect a bug, rather than replying to a month old one that's marked as **closed**. You can't expect anyone to read those.
